services:
  # 1. Broker & Cache (Filas)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # 2. API (FastAPI)
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    restart: always

  # 3. Background Worker (Celery)
  worker:
    build: .
    command: celery -A app.infrastructure.celery worker --loglevel=info -Q main-queue
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env
    restart: always
  
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - redis_insight_data:/data 

volumes:
  postgres_data:
  redis_insight_data: